[book]
authors = [ "Mathias Myrland"]
language = "en"
multilingual = false
src = "src"
title = "Performant web applications with DOMINATOR"

description = "Make highly performant web applications with Rust and DOMINATOR"

[output.html]
git-repository-url = "https://github.com/JedimEmO/dominator-book"

